<form method="post" action="login">
    <p>Введите имя:</p>
    <input type="text" name="loginName" placeholder="Имя"><br>
    <p>Введите пароль:</p>
    <input type="password" name="loginPassword" placeholder="Пароль"><br>
    <?php
        if (!empty($object->data->errors)) {
            echo "<br>" . $object->data->errors . "<br>";
        }
        if (!empty($object->data->successful)) {
            echo "<br>" . $object->data->successful . "<br>";
        }
    ?>
    <br>
    <input type="submit" name="loginSubmit">
</form>
<a href="index">Назад</a>