<form method="post" action="registration">
    <p>Введите имя:</p>
    <input type="text" name="name" placeholder="Имя"><br>
    <p>Введите пароль:</p>
    <input type="password" name="password" placeholder="Пароль"><br>
    <?php
        if (!empty($object->data->errors)) {
            echo "<br>" . $object->data->errors . "<br>";
        }
        if (!empty($object->data->successful)) {
            echo "<br>" . $object->data->successful . "<br>";
        }
    ?>
    <br>
    <input type="submit" name="submit">
</form>
<a href="index">Назад</a>